cstf/urls.py
from django.contrib import admin
from django.urls import path, include
from cstf import views

urlpatterns = [
    path('alta_integrante/', views.alta_integrante, name='alta_integrante'),
    path('cargar_estados/', views.cargar_estado, name='cargar_estado'),
    path('evaluar_cstf/<int:id>', views.evaluar_cstf, name='evaluar'),
]

gestorCstf/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls')),
    path('', include('usuarios.urls')),
    path('', include('proyectos.urls')),
    path('', include('cstf.urls')),
    path('', include('tribunal.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

proyectos/urls.py
from django.contrib import admin
from django.urls import path, include
from proyectos import views

urlpatterns = [
    path('presentar_proyecto/', views.presentar_proyecto, name='presentar_proyecto'),
    path('presentar_proyecto/cargar_alumnos/', views.cargar_alumnos, name='cargar_alumnos'),
    path('presentar_proyecto/cargar_docentes/', views.cargar_docentes, name='cargar_alumnos'),
    path('check_alumno/', views.check_alumno, name='check_alumno'),
    path('check_docente/', views.check_docente, name='check_docente'),
    path('alta_alumno/', views.alta_alumno, name='alta_alumno'),
    path('buscar_proyecto/', views.buscar_proyecto, name='buscar_proyecto'),
    path('cargar_rol/', views.cargar_rol, name='cargar_rol'),
    path('alta_docente/', views.alta_docente, name='alta_docente'),
    path('cargar_borrador/<int:id>', views.cargar_borrador, name='cargar_borrador'),
]

proyectos/models.py
from django.db import models
from usuarios.models import User
from django.contrib.auth.models import Group
from django.conf import settings
from django.core.mail import send_mail

#Definimos una funcion para path dinamico
def proyecto_ruta_subida(instance, filename):
    # Es llamada al hacer .save de la instancia en el formulario
    # 
    return f'proyectos/{instance.titulo}/{filename}'

class Proyecto(models.Model):
    titulo = models.CharField(max_length=200)
    descripcion = models.TextField()
    fPresentacion = models.DateTimeField(auto_now_add=True)
    certificadoAnalitico = models.FileField(upload_to=proyecto_ruta_subida)
    notaAceptacion = models.FileField(upload_to=proyecto_ruta_subida)
    curriculumAseso = models.FileField(upload_to=proyecto_ruta_subida)

class Alumno(models.Model):
    usuario = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    matricula = models.IntegerField()
    dni = models.CharField(max_length=12)
    nombre = models.CharField(max_length=200)
    apellido = models.CharField(max_length=200)
    mail = models.EmailField(max_length=200)

    def save(self, *args, **kwargs):
        if not self.usuario:
            user = User.objects.create_user(
                username = self.dni,
                password = f'{self.apellido}${self.dni}',
                email=self.mail
            )

            self.usuario = user

            subject = 'CSTF - Usuario dado de alta'
            message = f'Hola {self.nombre}, \n\n Tu cuenta ha sido creada. \n Usuario: {self.dni} \n\n contraseña: {self.apellido}${self.dni}. \n\n Una vez loguado cámbiala, por favor'
            from_email = settings.DEFAULT_FROM_EMAIL
            recipient_list = [self.mail]

            send_mail(subject, message, from_email, recipient_list)
        super().save(*args, **kwargs)

class Docente(models.Model):
    usuario = models.OneToOneField(User, on_delete=models.CASCADE)
    cuil = models.CharField(max_length=20)
    nombre = models.CharField(max_length=200)
    apellido = models.CharField(max_length=200)
    mail = models.EmailField(max_length=200, null=True)

    def __str__(self):
        return f'{self.nombre} {self.apellido}'

    def save(self, *args, **kwargs):
        if not self.usuario:
            # Check if the user associated with this Docente already exists
            existing_user = User.objects.filter(username=self.cuil).first()

            if existing_user:
                self.usuario = existing_user
            else:
                # If the user doesn't exist, create a new user
                new_user = User.objects.create_user(
                    username=self.cuil,
                    password=f'{self.apellido}${self.cuil}',
                    email=self.mail
                )
                self.usuario = new_user

                # Assign the user to a group (replace 'Docentes' with your group name)
                try:
                    docentes_group = Group.objects.get(name='docente')
                except Group.DoesNotExist:
                    # Create the group if it doesn't exist
                    docentes_group = Group.objects.create(name='docente')

                new_user.groups.add(docentes_group)

                # Send an email to the user with the generated password
                subject = 'CSTF - Usuario dado de alta'
                message = f'Hola {self.nombre}, \n\n Tu cuenta ha sido creada. \n Usuario: {self.cuil} \n\n contraseña: {self.apellido}${self.cuil}. \n\n Una vez loguado cámbiala, por favor'
                from_email = settings.DEFAULT_FROM_EMAIL
                recipient_list = [self.mail]

                send_mail(subject, message, from_email, recipient_list)

        super().save(*args, **kwargs)

class Rol(models.Model):
    rol = models.CharField(max_length=100)

    def __str__(self):
        return self.rol

#Relaciones
class Grupo(models.Model):
    idProyectoGrupo = models.ForeignKey(Proyecto, on_delete=models.CASCADE)

#Relaciones
class BorradorInforme(models.Model):
    idProyectoBorradorInforme = models.OneToOneField(Proyecto, on_delete=models.CASCADE)
    borradorInforme = models.FileField(upload_to='')
    aval = models.FileField(upload_to='')

#Relaciones
class Conforman(models.Model):
    idGrupo = models.ForeignKey(Grupo, on_delete=models.CASCADE)
    idAlumno = models.ForeignKey(Alumno, on_delete=models.PROTECT)
    analitico = models.FileField(upload_to='proyectos/', default='default.pdf', null=True)
    fechaAlta = models.DateTimeField(auto_now_add=True)
    fechaBaja = models.DateTimeField(null=True, blank=True)

#Relaciones
class DocenteProyecto(models.Model):
    idProyecto = models.ForeignKey(Proyecto, on_delete=models.CASCADE)
    idDocente = models.ForeignKey(Docente, on_delete=models.SET_NULL, null=True, blank=True)
    rol = models.ForeignKey(Rol, on_delete=models.PROTECT)

#Relaciones
class SeguimientoProyecto(models.Model):
    idProyecto = models.ForeignKey(Proyecto, on_delete=models.CASCADE)
    f_estado = models.DateTimeField(auto_now_add=True)
    estado = models.CharField(max_length=100)

proyectos/views.py
from django.http import JsonResponse
from django.shortcuts import render, redirect
from cstf.models import Estado
from usuarios.models import User
from .forms import BorradorInformeForm, DocenteProyectoForm, ProyectoForm, AlumnoForm, RolForm, DocenteForm, SearchForm, ConformanForm
from django.contrib.auth.decorators import login_required, permission_required
from .models import DocenteProyecto, Proyecto, Alumno, Grupo, Conforman, SeguimientoProyecto, Rol, Docente
from django.views.decorators.http import require_POST, require_GET
import json

# Create your views here.
@login_required(login_url='/login')
@permission_required("proyectos.add_proyecto", "/")
def presentar_proyecto(request):
    if request.method == 'POST':
        form = ProyectoForm(request.POST, request.FILES)
        if form.is_valid():
            proyecto = form.save(commit=False)
            proyecto.save()

            # Create a new Grupo instance and save it
            grupo = Grupo(idProyectoGrupo=proyecto)
            grupo.save()

            # Get the id of the created grupo
            grupo_id = grupo.id
            proyecto_id = proyecto.id

            # Store the grupo_id in the session
            request.session['grupo_id'] = grupo_id
            request.session['proyecto_id'] = proyecto_id
            print(grupo_id)

            estado = SeguimientoProyecto.objects.create(idProyecto=proyecto, estado="Carga del Proyecto")

            # Redirect to the new URL
            return redirect('/presentar_proyecto/cargar_alumnos/')
    else:
        form = ProyectoForm()
    
    return render(request, 'presentar_proyecto.html', {"form": form})

@require_GET
def check_alumno(request):
    dni = request.GET.get('dni', '')
    alumno = Alumno.objects.filter(dni=dni).first()

    if alumno:
        alumno_data = {
            'alumno_found': True,
            'alumno_id': alumno.id,
        }
    else:
        alumno_data = {'alumno_found': False}

    return JsonResponse(alumno_data)

@login_required(login_url='/login')
def cargar_alumnos(request):
    alumnos = None
    print(request.session['grupo_id'])
    if request.method == 'POST':
        form = ConformanForm(request.POST, request.FILES)

        # Assuming you have an 'alumno_id' field in your ConformanForm
        alumno_id = request.POST.get('alumno_id')
        print(alumno_id)

        if form.is_valid():
            # Retrieve the Alumno instance using alumno_id
            alumno = Alumno.objects.get(id=alumno_id)

            # Assign the Alumno instance to the form's 'alumno' field
            conforman_instance = form.save(commit=False)
            conforman_instance.idAlumno = alumno
            conforman_instance.idGrupo = Grupo.objects.get(id=request.session['grupo_id'])
            conforman_instance.save()
            print(conforman_instance)
            return redirect('/presentar_proyecto/cargar_alumnos/')

    else:
        form = ConformanForm()
        alumnos = list(Conforman.objects.filter(idGrupo=request.session['grupo_id']).select_related('idAlumno'))
        print(alumnos)
    return render(request, 'cargar_alumnos.html', {"form": form, 'alumnos': alumnos})


@require_GET
def check_docente(request):
    cuil = request.GET.get('cuil', '')
    docente = Docente.objects.filter(cuil=cuil).first()

    options_data = list(Rol.objects.all().values())       

    if docente:
        docente_data = {
            'docente_found': True,
            'docente_id': docente.id,
        }
    else:
        docente_data = {'docente_found': False}

    if options_data:
        docente_data['opciones'] = options_data
    else:
        roles = ["director", "co-director", "asesor"]
        rol_objects = [Rol(rol=rolNombre) for rolNombre in roles]

        # Using bulk_create on the model manager
        Rol.objects.bulk_create(rol_objects)

        # Retrieve the roles again
        options_data = list(Rol.objects.all().values())

        docente_data['opciones'] = options_data
        


    return JsonResponse(docente_data)

@login_required(login_url='/login')
def cargar_docentes(request):
    if request.method == 'POST':
        form = DocenteProyectoForm(request.POST)

        # Assuming you have an 'docente_id' field in your ConformanForm
        docente_id = request.POST.get('docente_id')

        if form.is_valid():
            # Retrieve the Alumno instance using alumno_id
            docente = Docente.objects.get(id=docente_id)

            # Asignamos la instancia de docente a la instancia de relación
            docenteProyectoInstance = form.save(commit=False)
            docenteProyectoInstance.idDocente = docente
            docenteProyectoInstance.idProyecto = Proyecto.objects.get(id=request.session['proyecto_id'])
            docenteProyectoInstance.save()

            return redirect('/presentar_proyecto/cargar_docentes/')  # Redirect to the desired URL after processing

    else:
        form = DocenteProyectoForm()
        docentes = list(DocenteProyecto.objects.filter(idProyecto=request.session['proyecto_id']).select_related('idDocente'))
        print(docentes)

    return render(request, 'cargar_docentes.html', {"form": form, 'docentes': docentes})

@login_required(login_url='/login')
@permission_required("proyectos.add_alumno", "/")
def alta_alumno(request):
    if request.method == 'POST':
        form = AlumnoForm(request.POST)
        if form.is_valid():
            # Create an Alumno instance but don't save it yet
            alumno = form.save(commit=False)

            # Check if the user associated with this Alumno already exists
            existing_user = User.objects.filter(username=alumno.dni).first()
            
            if existing_user:
                alumno.usuario = existing_user
            else:
                pass
                # If the user doesn't exist, create a new user
                new_user = User.objects.create_user(
                    username=alumno.dni,
                    password=f'{alumno.apellido}${alumno.dni}',
                    email=alumno.mail
                )
                alumno.usuario = new_user

                # You might want to send an email here as well

            # Save the Alumno instance with the associated user
            alumno.save()

            return redirect('/alta_alumno')

    else:
        form = AlumnoForm()

    return render(request, 'alta_alumno.html', {"form": form})

@login_required(login_url='/login')
def buscar_proyecto(request):
    proyecto_data = []

    # id provisto en la request?
    if 'proyecto_id' in request.GET:
        proyecto_id = request.GET['proyecto_id']
        # Filtramos y consultamos los objetos proyecto en db que coincidan con id
        proyectos = Proyecto.objects.filter(id=proyecto_id)
    else:
        proyectos = Proyecto.objects.all().order_by("-id")

    for proyecto in proyectos:
        # Obtenemos los estados del proyecto
        seguimiento_data = SeguimientoProyecto.objects.filter(idProyecto=proyecto)
        
        # Hacemos objeto ambos y los unimos a un array
        proyecto_data.append({
            'proyecto': proyecto,
            'seguimiento_data': seguimiento_data,
        })

    context = {'proyecto_data': proyecto_data}
    return render(request, 'buscar_proyecto.html', context)

@login_required(login_url='/login')
def cargar_rol(request):
    if request.method == 'POST':
        form = RolForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect("/")
    else:
        form = RolForm()

    return render(request, 'cargar_rol.html', {"form": form})

@login_required(login_url='/login')
@permission_required("proyectos.add_docente", '/')
def alta_docente(request):
    if request.method == 'POST':
        form = DocenteForm(request.POST)
        if form.is_valid():
            docente = form.save(commit=False)

            # Check if the user associated with this Alumno already exists
            existing_user = User.objects.filter(username=docente.cuil).first()
            
            if existing_user:
                docente.usuario = existing_user
            else:
                pass
                # If the user doesn't exist, create a new user
                new_user = User.objects.create_user(
                    username=docente.cuil,
                    password=f'{docente.apellido}${docente.cuil}',
                    email=docente.mail
                )
                docente.usuario = new_user

                # You might want to send an email here as well

            # Save the Alumno instance with the associated user
            docente.save()

            return redirect('/alta_docente')

    else:
        form = DocenteForm()

    return render(request, 'alta_docente.html', {"form": form})

@login_required(login_url='/login')
@permission_required("proyectos.add_borradorinforme", "/")
def cargar_borrador(request, id):
    if request.method == "POST":
        borrador = None
        form = BorradorInformeForm(request.POST, request.FILES)
        print(form)
        if form.is_valid():
            borrador = form.save(commit=False)
            borrador.idProyectoBorradorInforme = Proyecto.objects.get(id=id)
            borrador.save()
            estado = SeguimientoProyecto.objects.create(idProyecto=Proyecto.objects.get(id=id), estado="Carga del Borrador del Tf")
            return redirect('/')
    else:
        form = BorradorInformeForm()

    return render(request, 'cargar_borrador.html', {'form': form})

proyectos/templates/alta_alumno.html
{% extends 'base.html' %}

{% block title %}CSTF - Dar de alta como alumno{% endblock %}
{% load crispy_forms_tags %}

{% block content %} 
    <form action="" method="post">
        {% csrf_token %}
        {{form|crispy}}
        <button type="submit" class="btn btn-success">Dar de alta</button>
        <p>Si quieres unirte a un proyecto debes de darte de alta al proyecto <a href="/buscar_proyecto">Buscar Proyecto</a></p>
    </form>
{% endblock %}

proyectos/templates/alta_docente.html
{% extends 'base.html' %}

{% block title %}CSTF - Dar de alta docente{% endblock %}
{% load crispy_forms_tags %}

{% block content %} 
    <form action="" method="post">
        {% csrf_token %}
        {{form|crispy}}
        <button type="submit" class="btn btn-success">Dar de alta</button>
        <p>Si quieres unirte a un proyecto debes de darte de alta al proyecto <a href="/buscar_proyecto">Buscar Proyecto</a></p>
    </form>
{% endblock %}

proyectos/templates/base.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/css/select2.min.css" integrity="sha512-RZhhPUe7Rw4Dlu7PQKSTX4YMCYMbB2Kfnq1K8Yb/wVON9+5N3tSVr9Q8kqmMy08a5Vk9YY2vFq9GqiGpw5z4Zg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <title>{% block title%}CSTF{%endblock%}</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <img src="https://salud.unca.edu.ar/images/sitio/images/Logo_UNCA.jpg"
            width="70px" height="70px">
            <a class="navbar-brand" href="/">CSTF U.N.Ca</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="/">Inicio</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="proyectosDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Proyectos
                        </a>
                        <div class="dropdown-menu" aria-labelledby="proyectosDropdown">
                            <a class="dropdown-item" href="/buscar_proyecto">Ver Proyectos</a>
                            {% if user.groups.all.0.name == "cstf"  or user.is_superuser  %}
                                <a class="dropdown-item" href="/presentar_proyecto">Crear Proyecto</a>
                            {% endif %}
                        </div>
                    </li>
                    {% if user.groups.all.0.name == "cstf" or user.is_superuser %}
                    <li class="nav-item">
                        <a class="nav-link" href="/alta_alumno">Alta alumno</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/alta_docente">Alta docente</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/alta_integrante">Alta Integrante</a>
                    </li>
                    {% endif %}
                    <!-- Add more menu items here -->
                    {% if user.is_authenticated %}
                    <span class="navbar-text">Logged as {{ user.username }} {{ user.last_name }} |</span>
                    <li class="nav-item">
                        <a class="nav-link" href="/logout">Log out</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="/login">Login</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
    <div class="container-fluid">
        {% block content %}
        {% endblock %}
    </div>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script>
        // Initialize Bootstrap components
        $(document).ready(function () {
            $('[data-toggle="dropdown"]').dropdown();
        });
    </script>
</body>
</html>

proyectos/templates/cargar_alumnos.html
{% extends 'base.html' %}

{% block title %}CSTF - Agregar alumno al proyecto{% endblock %}
{% load crispy_forms_tags %}

{% block content %} 
    <form id="conforman-form" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        
        <!-- Hidden input field to store the alumno_id -->
        
        <div style="gap: 1em; display: flex;">
            <button type="button" id="check-alumno" class="btn btn-info">Check Alumno</button>
            <input type="hidden" id="alumno_id" name="alumno_id" value="">
            <button type="submit" class="btn btn-success" disabled>Submit</button>
            
        </div>
    </form>

    

    

    <h3>Alumnos en este proyecto</h3>
    <table class="table table-striped" style="padding: 1em !important;">
        <thead>
          <tr>
            <th scope="col">Alumno</th>
            <th scope="col">Fecha Alta</th>
            <th scope="col">Fecha Baja</th>
            <th scope="col">Dar de baja</th>
          </tr>
          {% for alumno in alumnos %}
            <tr>
                <td>
                    <p>{{alumno.idalumno.apellido}} {{alumno.idAlumno.nombre}}</p>
                </td>
                <td>
                    <p>{{alumno.fechaAlta|date:"Y-m-d H:i:s"}}</p>
                </td>
                <td>
                    <p>{{alumno.fechaBaja|date:"Y-m-d H:i:s"}}</p>
                </td>
                <td>
                    <button class="btn btn-danger">Baja</button>
                </td>
            </tr>
          {% endfor %}
        </thead>
    </table>

    <a style="padding-top: 1em;" href="/presentar_proyecto/cargar_docentes/"><button class="btn btn-primary">Cargar docente >></button></a>
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
    <script>
        $(document).ready(function () {
            $("#check-alumno").click(function () {
                var dni = $("#id_dni").val();  // Adjust the ID based on your form
                $.ajax({
                    url: "/check_alumno/",  // Replace with your actual URL
                    type: "GET",
                    data: { dni: dni },
                    success: function (data) {
                        if (data.alumno_found) {
                            alert("Alumno found with ID: " + data.alumno_id);
                            // Pass the alumno_id to the next view, for example, by storing it in a hidden input field
                            $("#alumno_id").val(data.alumno_id);
                            $("#conforman-form :submit").prop("disabled", false);
                        } else {
                            alert("Alumno not found!");
                        }
                    },
                    error: function () {
                        alert("Error checking Alumno.");
                    }
                });
            });
        });
    </script>
{% endblock %}

proyectos/templates/cargar_borrador.html
{% extends 'base.html' %}

{% block title %}CSTF - Cargar borrador Tf{% endblock %}
{% load crispy_forms_tags %}

{% block content %} 
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{form|crispy}}
        <button type="submit" class="btn btn-success">Cargar</button>
    </form>
{% endblock %}

proyectos/templates/cargar_docentes.html
{% extends 'base.html' %}

{% block title %}CSTF - Agregar docente al proyecto{% endblock %}
{% load crispy_forms_tags %}

{% block content %} 
    <form id="docente-form" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="button" id="check-docente" class="btn btn-info">Check Docente</button>
        <input type="hidden" id="docente_id" name="docente_id" value="">
        <button type="submit" class="btn btn-success" disabled>Submit</button>
    </form>

    <h3>Docentes en este proyecto</h3>
    <table class="table table-striped">
        <thead>
          <tr>
            <th scope="col">Docente</th>
            <th scope="col">Rol</th>
            <th scope="col">Dar de baja</th>
          </tr>
        </thead>
        {% for docente in docentes %}
            <tr>
                <td>
                    <p>{{docente.idDocente.apellido}} {{docente.idDocente.nombre}}</p>
                </td>
                <td>
                    <p>{{docente.rol.rol}}</p>
                </td>
                <td>
                    <button class="btn btn-danger">Baja</button>
                </td>
            </tr>
          {% endfor %}
    </table>

    <a style="padding-top: 1em;" href="/buscar_proyecto/"><button class="btn btn-primary">Terminar >></button></a>
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
    <script>
        $(document).ready(function () {
    $("#check-docente").click(function () {
        var cuil = $("#id_cuil").val();  // Adjust the ID based on your form
        $.ajax({
            url: "/check_docente/",  // Replace with your actual URL
            type: "GET",
            data: { cuil: cuil },
            success: function (data) {
                if (data.docente_found) {
                    alert("Docente encontrado: " + data.docente_id);
                    // Pass the docente_id to the next view, for example, by storing it in a hidden input field
                    $("#docente_id").val(data.docente_id);

                    // Clear existing options in the select
                    $("#rol_option").empty();

                    // Insert options retrieved from the server
                    for (var i = 0; i < data.opciones.length; i++) {
                        $("#rol_option").append('<option value="' + data.opciones[i].id + '">' + data.opciones[i].rol + '</option>');
                    }

                    $("#docente-form :submit").prop("disabled", false);
                } else {
                    alert("No hay docentes que coincidan");
                }
            },
            error: function () {
                alert("Error checking");
            }
        });
    });
});
    </script>
{% endblock %}

proyectos/templates/cargar_rol.html
{% extends 'base.html' %}

{% block title %}CSTF - Agregar Roles del docente en el proyecto{% endblock %}
{% load crispy_forms_tags %}

{% block content %} 
    <form action="" method="post">
        {% csrf_token %}
        {{form|crispy}}
        <button type="submit" class="btn btn-success">Cargar Rol</button>
    </form>
{% endblock %}

proyectos/templates/presentar_proyecto.html
{% extends 'base.html' %}

{% block title %}CSTF - Presentar Proyecto{% endblock %}
{% load crispy_forms_tags %}

{% block content %} 
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{form|crispy}}
        <button type="submit" class="btn btn-success">Cargar Proyecto</button>
    </form>
{% endblock %}